version: '3'
    
services:
  db:
    image: postgres
    environment:
       - POSTGRES_DB=marketplace
       - POSTGRES_USER=marketplace
       - POSTGRES_PASSWORD=marketplacepwd
  api:
    build: .
    command: prod-webservice
    environment:
      - MARKETPLACE_DEBUG=1
      - VIRTUAL_HOST=api.maketplace.local
      - CERT_NAME=api.maketplace.local
      - MARKETPLACE_SECRET_KEY=+!u6s@e[o|8"HYxOsysu_zaB@#qv!:5-dde[{)D2I8F^o)^GnDR/2uecja#co
      - MARKETPLACE_ALLOWED_HOSTS=api.maketplace.local
      - MARKETPLACE_DB_ENGINE=postgresql
      - MARKETPLACE_DB_HOST=db
      - MARKETPLACE_DB_NAME=marketplace
      - MARKETPLACE_DB_USER=marketplace
      - MARKETPLACE_DB_PASSWORD=marketplacepwd
      - MARKETPLACE_DB_PORT=5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db